import { DefaultTheme } from 'vitepress'

// Auto-generated by scripts/sync-navigation.mjs
// Do not edit manually.
export const generatedNav = [
  {
    text: 'Start here',
    link: '/start-here/'
  },
  {
    text: 'Navigate',
    link: '/navigate/'
  },
  {
    text: 'Operate',
    link: '/operate/'
  },
  {
    text: 'Learn',
    link: '/learn/'
  },
  {
    text: 'Mitigate',
    link: '/mitigate/'
  }
] as DefaultTheme.NavItem[]

export const generatedSidebar = [
  {
    text: 'Navigate',
    collapsed: false,
    items: [
      {
        text: 'Overview',
        link: '/navigate/'
      },
      {
        text: 'Wayfinding shortcuts',
        link: '/navigate/find'
      },
      {
        text: 'State',
        link: '/navigate/state-ledger'
      },
      {
        text: 'Monthly cadence',
        link: '/navigate/monthly-release'
      },
      {
        text: 'Band A guardrails',
        link: '/navigate/band-a'
      }
    ]
  },
  {
    text: 'Operate',
    collapsed: false,
    items: [
      {
        text: 'North Star & guardrails',
        link: '/operate/north-star-guardrails'
      },
      {
        text: 'Versioning & releases',
        link: '/operate/versioning-and-releases/'
      },
      {
        text: 'Sanitization checklist',
        link: '/operate/sanitization'
      },
      {
        text: 'Verify-in-10 guide',
        link: '/operate/verify-in-10'
      },
      {
        text: 'Decision spine',
        link: '/operate/decision-spine'
      },
      {
        text: 'Playbook canon',
        link: '/operate/'
      },
      {
        text: 'Signal registry',
        link: '/operate/signal-registry'
      },
      {
        text: 'Guardrail index',
        link: '/operate/guardrail-index'
      },
      {
        text: 'Cloudflare analytics',
        link: '/operate/cloudflare-analytics'
      }
    ]
  },
  {
    text: 'Learn',
    collapsed: false,
    items: [
      {
        text: 'Receipts & dashboards',
        link: '/learn/receipts'
      }
    ]
  },
  {
    text: 'Mitigate',
    collapsed: false,
    items: [
      {
        text: 'Fix: Interrupt flows',
        link: '/support/'
      },
      {
        text: 'Fix: Teams notifications',
        link: '/support/teams-notifications'
      },
      {
        text: 'Fix: Repo & pipeline access',
        link: '/support/access-repo-pipeline'
      }
    ]
  }
] as DefaultTheme.Sidebar
