import { DefaultTheme } from 'vitepress'

// Auto-generated by scripts/sync-navigation.mjs
// Do not edit manually.
export const generatedNav = [
  {
    text: 'Mitigate',
    link: '/mitigate/'
  },
  {
    text: 'Navigate',
    link: '/navigate/'
  },
  {
    text: 'Operate',
    link: '/operate/'
  },
  {
    text: 'Learn',
    link: '/learn/'
  }
] as DefaultTheme.NavItem[]

export const generatedSidebar = [
  {
    text: 'Navigate',
    collapsed: false,
    items: [
      {
        text: 'Overview',
        link: '/navigate/'
      },
      {
        text: 'Wayfinding shortcuts',
        link: '/navigate/find'
      },
      {
        text: 'State',
        link: '/navigate/state-ledger'
      },
      {
        text: 'New joiner FAQ',
        link: '/navigate/faq-new-joiners'
      },
      {
        text: 'Monthly cadence',
        link: '/navigate/monthly-release'
      },
      {
        text: 'SLI states map',
        link: '/navigate/sli-states'
      },
      {
        text: 'Band A guardrails',
        link: '/navigate/band-a'
      }
    ]
  },
  {
    text: 'Operate',
    collapsed: false,
    items: [
      {
        text: '20-minute handover',
        link: '/operate/handover-20-min'
      },
      {
        text: 'All runbooks',
        link: '/operate/runbooks-index'
      },
      {
        text: 'Decision spine',
        link: '/operate/decision-spine'
      },
      {
        text: 'Sanitization checklist',
        link: '/operate/sanitization'
      },
      {
        text: 'Playbook canon',
        link: '/operate/'
      },
      {
        text: 'Answer ledger pattern',
        link: '/operate/answer-ledger'
      },
      {
        text: 'Facilitation patterns',
        link: '/operate/facilitation'
      },
      {
        text: 'Handover RACI template',
        link: '/operate/handover-raci-template'
      },
      {
        text: 'Link Integrity',
        link: '/operate/link-integrity'
      },
      {
        text: 'North Star & Guardrails',
        link: '/operate/north-star-guardrails'
      },
      {
        text: 'Accessibility audit',
        link: '/operate/accessibility-audit'
      },
      {
        text: 'Accessibility quick wins',
        link: '/operate/accessibility-quick-wins'
      },
      {
        text: 'Anti-drift governance',
        link: '/operate/governance'
      },
      {
        text: 'Verify-in-10 guide',
        link: '/operate/verify-in-10'
      },
      {
        text: 'Community meeting pack',
        link: '/operate/community-pack'
      },
      {
        text: 'Policy-to-action example',
        link: '/operate/pattern-expense-sla'
      },
      {
        text: 'Versioning & releases',
        link: '/operate/versioning-and-releases/'
      },
      {
        text: 'Transition promises',
        link: '/operate/transition-operating-promises'
      },
      {
        text: 'Shared metric visibility',
        link: '/operate/shared-metric-visibility'
      },
      {
        text: 'State visibility map',
        link: '/operate/state-visibility'
      },
      {
        text: 'Cloudflare analytics',
        link: '/operate/cloudflare-analytics'
      },
      {
        text: 'Signal Registry',
        link: '/operate/signal-registry'
      },
      {
        text: 'Guardrail index',
        link: '/operate/guardrail-index'
      }
    ]
  },
  {
    text: 'Learn',
    collapsed: false,
    items: [
      {
        text: 'Learn',
        link: '/learn/'
      }
    ]
  },
  {
    text: 'Mitigate',
    collapsed: false,
    items: [
      {
        text: 'Mitigate',
        link: '/mitigate/'
      },
      {
        text: 'Fix: Teams notifications',
        link: '/support/teams-notifications'
      },
      {
        text: 'Fix: Repo & pipeline access',
        link: '/support/access-repo-pipeline'
      },
      {
        text: 'Fix: Interrupt flows',
        link: '/support/'
      }
    ]
  }
] as DefaultTheme.Sidebar
