// Auto-generated by scripts/sync-navigation.mjs
// Do not edit manually.
export const generatedNav = [
  {
    text: 'Overview',
    link: '/start-here/'
  },
  {
    text: 'Playbook',
    link: '/playbook/'
  }
] as const
export const generatedSidebar = [
  {
    text: 'Start',
    collapsed: false,
    items: [
      {
        text: 'Overview',
        link: '/start-here/'
      },
      {
        text: 'Wayfinding shortcuts',
        link: '/start-here/find'
      },
      {
        text: 'Quick-Run check',
        link: '/ops/quick-run'
      },
      {
        text: 'New joiner FAQ',
        link: '/faq-new-joiners'
      },
      {
        text: 'Release receipts',
        link: '/receipts/'
      },
      {
        text: 'Monthly cadence',
        link: '/monthly-release'
      },
      {
        text: 'SLI states map',
        link: '/start-here/sli-states'
      },
      {
        text: 'Band A guardrails',
        link: '/band-a'
      }
    ]
  },
  {
    text: 'Guides',
    collapsed: false,
    items: [
      {
        text: 'Decision Spine',
        link: '/decision-spine'
      },
      {
        text: 'Playbook',
        link: '/playbook/'
      },
      {
        text: 'Facilitation Techniques',
        link: '/facilitation'
      },
      {
        text: 'Accessibility Quick Wins',
        link: '/accessibility-quick-wins'
      },
      {
        text: 'Policy → Action Pattern (Expenses)',
        link: '/pattern-expense-sla'
      }
    ]
  },
  {
    text: 'Runbooks',
    collapsed: false,
    items: [
      {
        text: 'All runbooks',
        link: '/runbooks/'
      },
      {
        text: 'Link Integrity',
        link: '/runbooks/link-integrity'
      }
    ]
  },
  {
    text: 'Contributor Kit',
    collapsed: false,
    items: [
      {
        text: 'Sanitization Guidance',
        link: '/sanitization'
      },
      {
        text: 'Answer Ledger Pattern',
        link: '/answer-ledger'
      },
      {
        text: 'Anti-drift Content Governance',
        link: '/governance'
      }
    ]
  },
  {
    text: 'Fix it fast',
    collapsed: false,
    items: [
      {
        text: 'Interrupt flows',
        link: '/fix/'
      },
      {
        text: 'Teams notifications check',
        link: '/fix/teams-notifications'
      },
      {
        text: 'Repo & pipeline access',
        link: '/fix/access-repo-pipeline'
      },
      {
        text: 'Design system component',
        link: '/fix/ds-component-decision'
      },
      {
        text: 'Feature flag on staging',
        link: '/fix/flag-staging'
      },
      {
        text: 'VWO/Bloomreach sanity',
        link: '/fix/vwo-bloomreach-sanity'
      }
    ]
  }
] as const
